### ISSUE TITLE
Empty space between products

### ISSUE THREAD

**Issue by anamarija09** [GeneralMagicio/GM-swag-shop#25]
@kkatusic there is an empty space between products in the shop, when I hide some products the page number remains the same.
![swagshop](https://user-images.githubusercontent.com/110814947/192346314-88d4110c-0049-4a7c-9fb5-2a4a6854f825.png)

**Comment by kkatusic** [comment]
Fixed, these were showing product variations, but WooCommerce is excluding them from viewing.
