### ISSUE TITLE
Adding Google Tag Manager to our Swag Shop

### ISSUE THREAD

**Issue by ahmadabugosh** [GeneralMagicio/GM-swag-shop#28]
Hey @tomislavmamic 

Not sure who to tag, but can we please add Google Tag Manager to our Swag Shop site? (This would be the same code we have on our main site, so we can track traffic and transactions for our swag shop):

**To paste in the < head > of all pages:**

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WLQQCZP');</script>
<!-- End Google Tag Manager -->

```

**To paste at the beginning of the < body > of all pages:**

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WLQQCZP"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) --> 
```

**Comment by tomislavmamic** [comment]
Do you mean swag.generalmagic.io or ensmerchshop.xyz?

**Comment by ahmadabugosh** [comment]
@tomislavmamic swag.generalmagic.io , we already have another one installed on ENS

**Comment by tomislavmamic** [comment]
Okay, @kkatusic should do it in the WP, I am not so familiar with it.

**Comment by kkatusic** [comment]
@ahmadabugosh please check, tag code added

**Comment by ahmadabugosh** [comment]
Thanks @kkatusic looks good seems to be working!
