### ISSUE TITLE
Upgrade web3 swag shop product

### ISSUE THREAD

**Issue by ahmadabugosh** [GeneralMagicio/GM-swag-shop#29]
Thanks for the meeting yesterday @marthendalnunes ! 

For the next steps for this, we'll wait to hear from you on what tech stack, group of technologies and systems you would recommend we explore for a more modern composable swag shop implementation, then @tomislavmamic can start planning it out as a project and we can decide how to allocate resources for it (if we'll take it on as an internal project or build it for an upcoming client)

**Comment by tomislavmamic** [comment]
Closed because we decided to stay with current technologies for now.
