### ISSUE TITLE
Swag shop marketplace for impact DAOs

### ISSUE THREAD

**Issue by ahmadabugosh** [GeneralMagicio/GM-swag-shop#30]
hey @tomislavmamic , 

Since things are a bit calmer after the ENS launch, I thought it would be a good time to revisit the "Marketplace offering" for merch for Impact DAOs. 

As @Zeptimus has been reaching out to different DAOs there have been many he found that would like a very low cost option of just selling their merch through us (maybe with a small setup fee and we take 50% of revenue). 

I was thinking, an easy way to do this would be to just make different categories on our [own swag shop](https://swag.generalmagic.io/), and have a **marketplace** landing page on it that's on the menu. 

To start, we could also list the Giveth, TEC and Commons Stack merch there as well (crosspost it there) to seed the marketplace with items and let anyone buy their merch through us. 

Wdyt, can we do that?

**Comment by tomislavmamic** [comment]
I think that is a good idea, creating categories is easy enough.

**Comment by markoprljic** [comment]
This is a quick win solution. Great suggestion @ahmadabugosh 
Since this was 5 days ago, I would assume this could have been done already. 
@tomislavmamic ETA on making this happen?

**Comment by tomislavmamic** [comment]
We moved this into multiple separate tasks
